[package]
name = "shishua_rs"
version = "0.1.0"
authors = ["Dario Bartussek <d.bartussek@gmail.com>"]
edition = "2018"

[dependencies]
packed_simd_2 = { version = "0.3.4", features = ["into_bits"] }

rand_core = "0.5.1"

byteorder = "1.3.4"
